// Generated by https://quicktype.io

export interface MatchDetails {
    stat:         string;
    score:        string;
    description:  string;
    matchStarted: boolean;
    "team-1":     string;
    "team-2":     string;
    v:            string;
    ttl:          number;
    provider:     Provider;
    creditsLeft:  number;
}

export interface Provider {
    source:  string;
    url:     string;
    pubDate: string;
}
