// Generated by https://quicktype.io

export interface Match {
    matches:     MatchElement[];
    v:           string;
    ttl:         number;
    provider:    Provider;
    creditsLeft: number;
}

export class MatchElement {
    unique_id:         number;
    date:              string;
    dateTimeGMT:       string;
    "team-1":          string;
    "team-2":          string;
    toss_winner_team?: string;
    winner_team?:      string;
    squad:             boolean;
    matchStarted:      boolean;
    type:              Type;
    flag:              string;
}

export enum Type {
    Empty = "",
    FirstClass = "First-class",
    Odi = "ODI",
    Tests = "Tests",
    Twenty20 = "Twenty20",
}

export interface Provider {
    source:  string;
    url:     string;
    pubDate: string;
}
